apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: 2018-11-29T12:29:55Z
  labels:
    controller-uid: 7a222aae-f3d2-11e8-9a87-56c7ac7374a1
    job-name: my-job
  name: my-job
  namespace: default
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: 7a222aae-f3d2-11e8-9a87-56c7ac7374a1
  template:
    metadata:
      creationTimestamp: null
      labels:
        controller-uid: 7a222aae-f3d2-11e8-9a87-56c7ac7374a1
        job-name: my-job
    spec:
      containers:
      - command:
        - date
        image: busybox
        imagePullPolicy: Always
        name: my-job
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
